CACHED_CATEGORIES = []
CACHED_ERROR_MESSAGES = {}
CACHED_SUCCESS_MESSAGES = {}
CACHED_PRODUCTS_VISIBILITY_PER_PAGE = []
CACHED_PRODUCTS_SORTING_OPTION_NAMES = []
CACHED_PRODUCTS_SORTING_OPTION_VALUES = []